# PostgreSQL. Versions 8.2 and up are supported.

development:
  adapter: postgresql
  encoding: unicode
  database: randr_db
  pool: 5
  username: RaleighD
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: randr_db
  pool: 5
  username: RaleighD
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: randr_db
  pool: 5
  username: RaleighD
  password:
